### ISSUE TITLE
[suggestion] Linux build

### ISSUE THREAD

**Issue by skdza** [blindbandit76/virtual_pet#1]
Sir I saw this cool project from your reddit post and would like you to add a release build for linux to this repo!
You can build for linux from windows, since thats the os you use. Godot has cross build capabilities.

If you want I could also submit a linux build but you should trust yourself more with a build of a project then a rando on the internet.

I wish you well amazingly awesome stranger

**Comment by blindbandit76** [comment]
Thank you. I just didn't have a way to test if it works on linux. I will make a build for linux.
